// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGmoYlv5wTwK0R0uhIYtBIwzeL_z_Ml3w',
    appId: '1:251172256712:web:b5c4a9427d4cacb627defd',
    messagingSenderId: '251172256712',
    projectId: 'mp3-file-uploader',
    authDomain: 'mp3-file-uploader.firebaseapp.com',
    storageBucket: 'mp3-file-uploader.appspot.com',
    measurementId: 'G-E7NVXCSJ2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvIi4NBTdgqhwmLrHgZKiC94HIWxk6ssE',
    appId: '1:251172256712:android:fa4d877f66faee8427defd',
    messagingSenderId: '251172256712',
    projectId: 'mp3-file-uploader',
    storageBucket: 'mp3-file-uploader.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-IIjs-dR9kGhB4O5Ar1QIaT0Ct4AZGHo',
    appId: '1:251172256712:ios:c3091610bee8ee0827defd',
    messagingSenderId: '251172256712',
    projectId: 'mp3-file-uploader',
    storageBucket: 'mp3-file-uploader.appspot.com',
    iosClientId: '251172256712-omr7g1bfkrrgg1j280pa2rl5k144f1h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mp3FileUploader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-IIjs-dR9kGhB4O5Ar1QIaT0Ct4AZGHo',
    appId: '1:251172256712:ios:c3091610bee8ee0827defd',
    messagingSenderId: '251172256712',
    projectId: 'mp3-file-uploader',
    storageBucket: 'mp3-file-uploader.appspot.com',
    iosClientId: '251172256712-omr7g1bfkrrgg1j280pa2rl5k144f1h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mp3FileUploader',
  );
}
